DROP TABLE IF EXISTS t_user;
CREATE TABLE t_user (
   ID             INT(11) NOT NULL AUTO_INCREMENT,
   EMAIL          VARCHAR(100) NOT NULL,
   PASSWORD       VARCHAR(100) NOT NULL,
   FIRSTNAME      VARCHAR(50),
   LASTNAME       VARCHAR(50),
   CONSTRAINT PK_USER PRIMARY KEY (ID)
);

INSERT INTO t_user (EMAIL, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('admin@test.com','$2a$12$fV0rJ7oF3NWAm3RIV38WBOy4bipG9YkmulyBG8.zFqaYXnHyGPz4a','Admin','Admin');

DROP TABLE IF EXISTS role;
CREATE TABLE role (
    ID            VARCHAR(100) NOT NULL,
	NAME          VARCHAR(100) NOT NULL,
	CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

INSERT INTO role (ID,NAME) VALUES ('ROLE_ADMIN','Role Administrator');
INSERT INTO role (ID,NAME) VALUES ('ROLE_USER','Role User');

DROP TABLE IF EXISTS userrole;
CREATE TABLE userrole (
    EMAIL         VARCHAR(100) NOT NULL,
	ROLEID        VARCHAR(100) NOT NULL,
	CONSTRAINT PK_USERROLE PRIMARY KEY (EMAIL,ROLEID)
);

INSERT INTO userrole VALUES ('admin@test.com','ROLE_ADMIN');

DROP TABLE IF EXISTS t_publisher;
CREATE TABLE t_publisher (
    PUBID         INT(11) NOT NULL AUTO_INCREMENT,
    PUBNM         VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PUBLISHER PRIMARY KEY (PUBID)
);


DROP TABLE IF EXISTS t_book;
CREATE TABLE t_book (
    BOOKID        INT(11) NOT NULL AUTO_INCREMENT,
	BOOKNM        VARCHAR(100),
	BOOKAUTHOR    VARCHAR(100),
	BOOKISBN      VARCHAR(50),
	PUBID         INT(11),
	CONSTRAINT PK_BOOK PRIMARY KEY (BOOKID)
);
