DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER (
   ID             INT(11) NOT NULL AUTO_INCREMENT,
   EMAIL          VARCHAR(100) NOT NULL,
   PASSWORD       VARCHAR(100) NOT NULL,
   FIRSTNAME      VARCHAR(50),
   LASTNAME       VARCHAR(50),
   CONSTRAINT PK_USER PRIMARY KEY (ID)
);

INSERT INTO T_USER (EMAIL, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('admin@test.com','$2a$12$fV0rJ7oF3NWAm3RIV38WBOy4bipG9YkmulyBG8.zFqaYXnHyGPz4a','Admin','Admin');

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE (
    ID            VARCHAR(100) NOT NULL,
	NAME          VARCHAR(100) NOT NULL,
	CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

INSERT INTO ROLE (ID,NAME) VALUES ('ROLE_ADMIN','Role Administrator');
INSERT INTO ROLE (ID,NAME) VALUES ('ROLE_USER','Role User');

DROP TABLE IF EXISTS USERROLE;
CREATE TABLE USERROLE (
    EMAIL         VARCHAR(100) NOT NULL,
	ROLEID        VARCHAR(100) NOT NULL,
	CONSTRAINT PK_USERROLE PRIMARY KEY (EMAIL,ROLEID)
);

INSERT INTO USERROLE VALUES ('admin@test.com','ROLE_ADMIN');


DROP TABLE IF EXISTS T_BOOK;
CREATE TABLE T_BOOK (
    BOOKID        INT(11) NOT NULL AUTO_INCREMENT,
	BOOKNM        VARCHAR(100),
	BOOKAUTHOR    VARCHAR(100),
	BOOKISBN      VARCHAR(50),
	CONSTRAINT PK_BOOK PRIMARY KEY (BOOKID)
);
